### ISSUE TITLE
gradelib-lab4 expecting output different than show_vmas produces

### ISSUE THREAD

**Issue by TotalKnob** [vusec/aos-labs#2]
The output of show_vmas is different from the output as is expected by grade-lab4. The latter tries to match output in the form:
'0x0000000000200000 - 0x0000000000201000 .rw-. .data',
'0x0000000000800000 - 0x0000000000801000 .r-x. .text',
'0x0000000000801000 - 0x0000000000802000 .r--. .rodata',
'0x0000000000802000 - 0x0000000000803000 .rw-. .data',
'0x00007fffffffd000 - 0x00007fffffffe000 .rw-. stack', ...

while show_vmas produces output including prepended whitespaces, the file backing and quoted names:
'  0x0000000000200000 - 0x0000000000201000 [rw-] 0xffff800000290c3c - 0x0000000000000012 ".data"'
'  0x0000000000800000 - 0x0000000000801000 [r-x] 0xffff80000028eacc - 0x0000000000000f7b ".text"'
'  0x0000000000801000 - 0x0000000000802000 [r--] 0xffff800000290974 - 0x0000000000000250 ".rodata"'
'  0x0000000000802000 - 0x0000000000803000 [rw-] 0xffff800000290bd4 - 0x0000000000000068 ".data"'
'  0x00007fffffffd000 - 0x00007fffffffe000 [rw-] "stack"'

While including the file backing info might be useful for debugging, it might be obsolete and is inconsistent with the grading lib.

**Comment by sirmc** [comment]
The tests mainly use the output from the function `print_vmas()`, so the output of `show_vmas()` should not matter AFAIK (although I'm not 100% sure that this is true for all tests, some might expect a fault in user-space).
